# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    self.driver.get("https://adminqa.neapro.site/login/")
    self.driver.find_element(By.ID, "admin_email").click()
    self.driver.find_element(By.ID, "admin_email").send_keys("moderat@neapro.ru")
    self.driver.find_element(By.ID, "admin_password").click()
    self.driver.find_element(By.ID, "admin_password").send_keys("Aa123456")
    self.driver.find_element(By.NAME, "commit").click()
    self.driver.find_element(By.LINK_TEXT, "Сотрудники").click()
    self.driver.find_element(By.LINK_TEXT, "Администраторы").click()
    self.driver.find_element(By.LINK_TEXT, "Создано").click()
    self.driver.find_element(By.ID, "batch_action_item_72").click()
    self.driver.find_element(By.LINK_TEXT, "Удалить").click()
    assert self.driver.switch_to.alert.text == "Вы уверены, что хотите удалить это?"
    self.driver.switch_to.alert.accept()
  
